# Generated by Django 5.0 on 2023-12-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alien_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Human",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("human_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Spaceship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spaceship_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AlienKill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kill_date", models.DateField()),
                (
                    "alien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.alien"
                    ),
                ),
                (
                    "human",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.human"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment_date", models.DateField()),
                (
                    "alien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.alien"
                    ),
                ),
                (
                    "human",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.human"
                    ),
                ),
                (
                    "spaceship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.spaceship"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Escape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abduction_date", models.DateField()),
                (
                    "alien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.alien"
                    ),
                ),
                (
                    "human",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.human"
                    ),
                ),
                (
                    "spaceship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.spaceship"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Abduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abduction_date", models.DateField()),
                (
                    "alien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.alien"
                    ),
                ),
                (
                    "human",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.human"
                    ),
                ),
                (
                    "spaceship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.spaceship"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_date", models.DateField()),
                (
                    "alien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.alien"
                    ),
                ),
                (
                    "spaceship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.spaceship"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkingTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "human",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.human"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.tour"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transportation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transportation_date", models.DateField()),
                (
                    "alien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.alien"
                    ),
                ),
                (
                    "human",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.human"
                    ),
                ),
                (
                    "spaceship_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transports_from",
                        to="db.spaceship",
                    ),
                ),
                (
                    "spaceship_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transports_to",
                        to="db.spaceship",
                    ),
                ),
            ],
        ),
    ]
