# Generated by Django 5.0 on 2023-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="humans",
            field=models.ManyToManyField(to="db.human"),
        ),
    ]
