# Generated by Django 5.0 on 2023-12-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_experiment_name_tour_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="humans",
        ),
        migrations.AddField(
            model_name="tour",
            name="human",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="db.human"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tour",
            name="name",
            field=models.CharField(default="tour", max_length=100),
        ),
    ]
